name: Full Flutter CI

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
    - "docs/**"
    - "README.md"
  push:
    branches:
      - master
    paths-ignore:
      - ".github/**"
      - "docs/**"
      - "README.md"
      - "res/**"
      - "appimage/**"
      - "flatpak/**"

#权限
permissions: write
jobs:
  create_issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write

  #编译完成后是否上传
  run-ci:
    uses: ./.github/workflows/flutter-build.yml
    with:
      upload-artifact: true
